import turtle

turtle.pensize(3) 
turtle.penup() 
turtle.goto(-400, -50)
turtle.pendown()
turtle.right(60)
turtle.begin_fill()
turtle.color("red")
turtle.circle(80, steps = 3) 
turtle.end_fill()

turtle.penup()
turtle.goto(-200, -50)
turtle.pendown()
turtle.left(15)
turtle.begin_fill()
turtle.color("blue")
turtle.circle(80, steps = 4)
turtle.end_fill()

turtle.penup()
turtle.goto(0, -50)
turtle.pendown()
turtle.left(9)
turtle.begin_fill() 
turtle.color("green")
turtle.circle(80, steps = 5) 
turtle.end_fill()

turtle.penup()
turtle.goto(200, -50)
turtle.pendown()
turtle.left(6)
turtle.begin_fill() 
turtle.color("yellow")
turtle.circle(80, steps = 6) 
turtle.end_fill() 

turtle.penup()
turtle.goto(400, -50)
turtle.pendown()
turtle.left(7.5)
turtle.begin_fill() 
turtle.color("purple")
turtle.circle(80, steps = 8)
turtle.end_fill()

turtle.color("green")
turtle.penup()
turtle.goto(-330, 100)
turtle.pendown()
turtle.write("Cool Colorful Shapes",
             font = ("Times", 64, "bold"))

turtle.hideturtle()
turtle.done()
             
